Remove, postpone, complete Task, restructuring.
RodionShyshkin/ToDoList pull request #11
Opened 2020-08-14 17:48 UTC by RodionShyshkin

Memory model classes were restructured, remove, postpone and completeTask methods were added.

2020-08-14 18:18 UTC, ValeriiSudakov requested changes

2020-08-14 18:18 UTC, ValeriiSudakov commented on src/API/TaskService.cpp
> +  for(auto task : todayTasks) {
it's better to use const auto&

2020-08-14 18:18 UTC, ValeriiSudakov commented on src/MemoryModel/Storage/FullStorage.cpp
> +  if(!task_storage_.PushTask(task_ptr)) return OperationResult::create(ErrorCode::WRONG_TASK_ID);
PushTask.. you should to rename

2020-08-14 18:18 UTC, ValeriiSudakov commented on src/MemoryModel/Storage/TaskView.cpp
> +  for(auto it = map.begin(); it != map.end(); ++it) {
why dont u use const auto& : map ?

2020-08-14 18:18 UTC, ValeriiSudakov commented on src/MemoryModel/Storage/TaskView.cpp
> +  if(!removeFromMap(id, date_sorted_)) return false;
If 1 of remove returned false - other will not be removed...

2020-08-14 18:18 UTC, ValeriiSudakov commented on src/MemoryModel/Storage/TaskView.cpp
> +    for(auto it = first; it != priority_sorted_.end(); ++it) {
Why do u use different iterators in same loops?

2020-08-14 18:18 UTC, ValeriiSudakov commented on src/MemoryModel/Task/TaskEntity.cpp
> +TaskID TaskEntity::GetParentID() const { return parent_id_; }
Add spaces between methods..............

2020-08-14 18:18 UTC, ValeriiSudakov commented on src/MemoryModel/Task/TaskEntity.h
> +  std::map<TaskID, std::shared_ptr<TaskEntity>>           subtasks_;
R u sure, that shared ptr is necessary here? mb weak ptr?

2020-08-17 08:23 UTC, IliaIlyin approved these changes

2020-08-17 09:05 UTC, denys-hrulov approved these changes

2020-08-17 09:06 UTC, merged